---
title: "Clinical Background"
---

<br>

Throughout my clinical training, I have worked with people struggling with trauma, intense emotions, suicidal thoughts and behaviors, personality disorders, anxiety, depression, and other mental health difficulties I also help clients with concerns related to relationships, general stress, and identity. For all clients, and particularly for those who have experienced trauma or stressful life events, I believe in creating a space that feels safe to process and work towards acceptance, peace, and healing.

I take great pride in empowering my clients to view themselves and their world with a little more kindness and compassion. My therapeutic style reflects warmth, understanding, and nonjudgmental curiosity. I work together with clients to help identify how therapy can best help them address their current difficulties and achieve their treatment goals. My approach is guided by evidence-based practices, including dialectical behavior therapy (DBT), cognitive processing therapy (CPT) for trauma, cognitive behavioral therapy (CBT), acceptance and commitment therapy (ACT), emotion focused therapy (EFT), and exposure and response prevention (ERP).

Across treatment approaches, I consider client input and feedback to be essential. I strive to tailor therapy to meet the needs, goals, and values of each individual. Therapy is an opportunity to not only address current difficulties, but also to build upon existing sources of strength and resilience. 

<br>

# Credentials

<br>

I am in the last year of my Ph.D. in clinical psychology and am currently completing my clinical internship at the Orlando VA Medical Center. Prior to this, I completed practicum experiences at the Tampa Bay Center for Relational Psychology, Bay Pines VA Hospital, Rogers Behavioral Health Center, and the USF Psychological Services Center. I am a member of the Association of VA Psychologist Leaders, American Association of Suicidology, and Psi Chi National Honor Society in Psychology. 
