---
title: "Research"
---

<br>

I am passionate about improving suicide risk assessment and intervention. I research individual characteristics that may affect one's vulnerability or resilience in the face of negative life events.  In particular, I am interested in understanding how *perfectionism* may affect responses to certain negative life events, and how this might contribute to poorer mental health outcomes —-- up to and including suicide risk. Relatedly, I evaluate how we can best train mental health professionals to help suicidal clients cope with negative life events. As part of this research, I have assisted in writing and preparing grants submitted to SAMHSA and NIMH, and have conducted data analyses and write-ups for quarterly, annual, and final grant reports. 

<br>

# Academic Works

* **Doctoral Dissertation**
  + *An Experimental Study of Negative Performance Feedback: Consideration of a Cognitive Pathway and Individual Difference Factors,* University of South Florida, 2021
* **Master's Thesis**
  + *Perfectionism, Negative Life Events, and Cognitive Appraisal: A Contextual Model of Perfectionism’s Maladaptive Nature,* University of South Florida, 2020
* **Honors Thesis**
  + *Connecting Attachment Style to Resilience: Contributions of Self-Care and Self-Efficacy,* University of Kansas, 2017

<br>

# Peer-Reviewed Publications

* Schuck, A., Gryglewicz, K., **Bender, A.**, Nam, E., McNeill, M., Rosler, M., Cosare, M., & Karver, M. (In Press). Examining the effectiveness of a family-focused training to prevent youth suicide. *Family Relations*.

* **Bender, A.**, Peterson, A., Schuck, A., & Karver, M. (2021). [Perfectionism, Negative Life Events, and Cognitive Appraisal: A Contextual Model of Perfectionism’s Maladaptive Nature](https://link.springer.com/content/pdf/10.1007/s10942-021-00437-9.pdf). *Journal of Rational-Emotive & Cognitive-Behavior Therapy*, 1-20.

* Gleason, L., **Bender, A.**, Chen, J., Bozzay, M., Brown-Hangartner, R., Romero, G., Labouliere, C., Elzy, M., Gryglewicz, K., & Karver, M., (2021). [Under the Surface: The Role of Covert Cues in Peer Suicide Risk Referrals](https://link.springer.com/article/10.1007/s12310-021-09459-1). *School Mental Health*, 1-11. 

* **Bender, A.**, Schuck, A., Peterson, A., Rosler, M., Gryglewicz, K., & Karver, M. (2021). [LINC to Life: Evaluation of a Safety Planning Training Program with Mental Health Professionals](https://www-tandfonline-com.ezproxy.lib.usf.edu/doi/pdf/10.1080/13811118.2021.1911893). *Archives of Suicide Research*, 1-17.

* Peterson, A., **Bender, A.**, Sullivan, B., & Karver, M. (2021). [Ambient Discrimination, Victimization, and Suicidality in the LGBTQ Population](https://link-springer-com.ezproxy.lib.usf.edu/content/pdf/10.1007/s10508-020-01888-4.pdf). *Archives of Sexual Behavior, 50*(3), 1003-1014.

* Peterson, A., Monahan, M., **Bender, A.**, & Karver, M., (2020). [Don’t Invite Everyone! Training Variables Impacting the Effectiveness of QPR Trainings](https://link-springer-com.ezproxy.lib.usf.edu/content/pdf/10.1007/s10488-020-01078-3.pdf). *Administration and Policy in Mental Health and Mental Health Services Research, 48*(2), 343-353.

* Peterson, A., Bozzay, M., **Bender, A.**, Monahan, M., & Chen, J. (2020). [Those left behind: A scoping review of the effects of suicide exposure on veterans, service members, and military families](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8162890/pdf/nihms-1702069.pdf). *Death Studies*, 1-10.

* Devendorf, A., **Bender, A.**, & Rottenberg, J. (2020). [Depression presentations, stigma, and mental health literacy: A critical review and YouTube content analysis](https://pdf.sciencedirectassets.com/271858/1-s2.0-S0272735820X00043/1-s2.0-S0272735820300313/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjECoaCXVzLWVhc3QtMSJGMEQCIHvq3SDQUiGEBeS3ATsE7q5wMGJO9TPtSUdS0sPGuaNoAiB48i0vz9S1R9%2Fqt4QeQPsROPSyBFQwTOr9Nu5fiGzMciqDBAiy%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAQaDDA1OTAwMzU0Njg2NSIMi6%2Fqi4Imle%2FZ%2B45PKtcDF50pmU8PnwK8YvGgU01R6EGfEyvPcpSgVyhDsMr17%2FANW8%2BPIyha5J4ULO%2FGznLANAF9hJUvA%2BkE3L2pEEAjz3lijPVN26ZWnKrvIv8RaxqnfwYa5mjC3th1MKH5tkDw%2FV3K142Z5L5ep2UMG3PCfgfhTxjWE%2BDNeQtPnG6LKylccCy7xjPgE9h93BoZCe23lnWLcwngtHWYhI1kUxrdSahh3VqmJ6QrudnYbd%2BlqXUbFXTYoVLzkgbsucKiXj9sps%2BZuB4sPijjkk4in3xpluFTd7D7hxPuQVG%2FRB49iz9qNg5ikrRCYeObuHAP%2Bj6zW6N%2FiHWj1oVMwNDY%2BVshQ1fZzj3fB%2B%2BVX%2FRNK4BNvI315GhVwHBINbMnlt9muN9R3%2Fa9vnt%2BjRiR3bhcWyOA0JefootH%2FL45SLzDJus5OgorUimFa6acMbmDp%2BX5TMv5F2LTSPWYely%2FGfY20f1F%2BwF08irye4A1gS3oKOrPaTVdKcCwYW%2FPl4LoZDcRx6eIlOlvdHJ9ZIbMhfLWBCgNy3GfgfOO0N2PTTjfRcVbPahoE9881QsZbkAaZfWdVjIZwz%2BnNzTrjKopkeBxuHwqwQFiNL0lRz1zoTgInU2fdBYP0N4xorZOMMaXhJIGOqYBydyESbr5B8AIQSBriCSLJS0K64kZDSfVzE5FS1vUva6Fi%2Bsg2nHR%2F8RM%2BOPxsR6UGWEEOFYu77X5AqNkXizZTlavdCuWUigWbiBWMBXFWEASKZHDdfm8S079tgSOY574mqhijhlE4kRZwrbFsMz5936YlKBUNOs0JeNgvZA6dks8kKyaD76B%2FGTBKWmpR06UYluVCB24IuC4tYkpoxI33EncAAUmoA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220328T021245Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAQ3PHCVTYTZQKXOYE%2F20220328%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=a94f963b156fd9b1339bb38c94644253eb78de490abd1ccafca197fc0453f96f&hash=f34bef632ca359492c92812287fc3047bfa061e10448c488c202ea9ac56d4f4e&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=S0272735820300313&tid=spdf-a117313f-0f61-46e4-bb30-43a0ca107f18&sid=0389df3452be55427279a5d02aa713fa07d9gxrqa&type=client&ua=4c09500c05500d570201&rr=6f2cd7b5da0667bc). *Clinical Psychology Review, 78*, 101843.

* Gryglewicz, K., Monahan, M., Chen J., Bozzay, M., **Bender, A.**, Gleason, L., Witmeier M., & Karver, M. (2019). [Examining the Effects of Role Play Practice in Enhancing Clinical Skills to Assess and Manage Suicide Risk](https://www-tandfonline-com.ezproxy.lib.usf.edu/doi/pdf/10.1080/09638237.2018.1521936?needAccess=true). *Journal of Mental Health*, 1-9. 

* **Bender, A.** & Ingram, R. (2018). [Connecting Attachment Style to Resilience: Contributions of Self-Care and Self-Efficacy](https://pdf.sciencedirectassets.com/271782/1-s2.0-S0191886918X00063/1-s2.0-S0191886918301648/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjECoaCXVzLWVhc3QtMSJGMEQCIEjJyEzoJOj0B4h1mJhr4S%2FVb2D2saaRGkNt4jGXhn%2FXAiAxp03b%2FFfG7MoxNCTiW7aVAI379y6YxemG6blxUSAxHCqDBAiz%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAQaDDA1OTAwMzU0Njg2NSIM3dVVgEcpBpDjBEhCKtcDlVh0XMJ5xXOFNhfQRfTLSY%2BXjtWN2tv6ehJy6zixCmVB%2B%2FXzR7dQyuoJxv1i6xN1i1ESF%2FgDn3lJbK1Asw16FqGpw7khzTjfhV3BFQVhCr54wjH7QaWQHKHXNtlJr6agG9PbAA2bvvtNqKp%2FHCD4pLyfLL4fDw8ePBnV1%2B%2Fyb80SGYfajdWSL4%2FC9eKPEoqE83h3gHZFi6cVeiQNT6c%2FTbCpIp88wo%2FT0mnwaSHJHOZjDf1TjTGBBZFGXxsTercRteCUYVR858rj1iYwDNRJafGe4EPLlIxMyh%2F5kAARdYVKAKcNQsSdif6FNld6AU2Ys7sWPVG03jYPV%2FyWU3zGuMke6oHq%2BhDRSGiO11zYN3gNDK93JoN0k6mi%2BqP2MK%2BURy8ujcEGOuTYPI82XKxRNew4tVDHuKSvnrgTBHBRfrZ4RhrCXm%2Bql%2BdfWG5P4Nod9M%2F6b85rR0fcmIpDXgMcnkNwhbPStuj9A3EXO6vUDkULya2zM0%2FTnQQPxvpf1uS6dsqIUtprUkDYE9k7VjB0GSM1KF5TUZ%2FkoEUYIVxABpJy30Xx7QAIC999cooTLgbQZOKAN3PxVaVEF%2BIaFvg6Z%2FdiDu34apjzOWWxKuDpT1iVpI3HfYGUMJSihJIGOqYBQA8bnUvty02KDREHvS8cssja1krVjjq%2B%2B6TLRuYYc6aVWOtkqoNmtShbYJPIDdWbL%2BqbVeoc15KHB3T1umjeH%2BOatw8%2FtJrUuxEFLKZ9EiV%2FbbkSWjmlbg7o4PC%2BQUP07nlGbugDkuPCaLBdHLiTiqCwZNBHriQnXBiNlNzCzpTts%2BhGCK2GVbWvqJwIfZ5XV3ralX%2BpomcWjVI96rdvJP8zSKVReA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220328T021623Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAQ3PHCVTYVAOK5EE6%2F20220328%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=5895189eb9e5590bb375a08bdb2246413c476cc6c64cd711928027b272365657&hash=0cc91989060800d1921e2c7fc5b9a11c05fca402c34a9fb6fe0b5816375e0b49&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=S0191886918301648&tid=spdf-b5de9be3-e05e-4627-b908-02b3ce7f6ecf&sid=0639d38550fae744d2283b3-22a48adbd8c0gxrqa&type=client&ua=4c09500c05035f5a0401&rr=6f2cdd08ba1f8dae). *Personality and Individual Differences, 130*(1), 18-20. 

* **Bender, A.**, Hagan, K., & Kingston, N. (2017). [The Association of Folate and Depression: A Meta-Analysis](https://pdf.sciencedirectassets.com/271251/1-s2.0-S0022395617X00083/1-s2.0-S0022395617305927/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjECsaCXVzLWVhc3QtMSJIMEYCIQCexlK03fMaIwgDKJ11kuPFORKh%2BaIqtfeTl%2FJ63Oi2WwIhAPeua99QMBm1Sf%2BxvqRuN7%2FMumeOlGf8R6mMURLpwzxLKoMECLP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQBBoMMDU5MDAzNTQ2ODY1IgylhkmxlE83hbq%2F30sq1wN4HwlYA27y%2BhW1ONcSADO10KecRC76pLZOHN3zfCFcQ2aCOaRJ5qzP3XUf0kMNjx95ttkR%2BZKYiy9U7PnCOTVbLvucUmw63XbYuiO5ozCUrOqA2BxKCfH7cK%2Be8ztwV2D6HogwuPK%2F8%2BLxoJL6Zv4hLN7WMC3aM%2BKDPfB8A8qbBdyWVfT40mtN95gW77Z5uwhhNIQBOHNVM35AyeUHm6pDiF1P4SGMmDNpeeCAZxRMXWx1tMBDSzZtsDdAPFk%2BLoLXnnv%2BozOCsVhGq0bmF8mWoSXuzKTBnPuIKcB3inYaKP6XdhQpYP%2Fo7TZ3HItaJAt2MVKPypkRDP%2BQlXlQ6zspck9A6ACALUsBigOGEvhYZ6rdjtHp6%2FHARi4tpwEIxp0qEHMFtOwaipZ%2BEaXaqdGrqBATJUIwgBb7l7rQ44oNeOvpQf08RXKplLNm0Q1EixuAVcG%2FMsxrwVeVQkCeVEbY%2B2Yp9%2F97N3BkjH9SOhsjPj1d7kpZV6aB4ZEqH%2Bv1VK0ckU0rbVXc%2FDdYN1c%2BANtIwRExRQT9dHORUzpc47jXMq%2BQuWVrZrSpE2HO9oAklMGd6wphJcw4wWDkl8pWDMuegFda%2BwHv58tvQI1TamU%2BX3N%2F2HtU9qow1bOEkgY6pAFos%2F46CBwpJ0NYUz0X1mAROG%2BFUbcdKIaPXsYYOz8ntJySnI23xt2foHC42Frtu%2FnJlQEsLMfs5d%2Bdm2GCz1%2FSVCXFaMe3mogP%2FYJpzcz7DWajSQ5KHyyNhNNu4cEvRTLHduNInrts9wlMmNMx7DORQASRwN6w%2Bcjbo%2FY0DUtB%2B3u4qAtotTSOrXYSPY1ubBhc5t7x3vzGYBMUoWld2Fa7jyzn8A%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220328T021648Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAQ3PHCVTY7UVVPO7L%2F20220328%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=658df25d67a6b20bad7a95c2f4a9f7569485e49ccac0acf2edda9a5ca3192377&hash=25f441b9ea58d7be00b250e8a2e265bbdaba25f9ed189bc6e7998512a934ee83&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=S0022395617305927&tid=spdf-4b931b8e-7ab5-47fa-bf50-6d6a93c78e24&sid=0639d38550fae744d2283b3-22a48adbd8c0gxrqa&type=client&ua=4c09500c05030e5a5604&rr=6f2cdda80de467de). *Journal of Psychiatric Research, 95*, 9-18.










